In [1]:
import numpy as np



X = np.random.random((5,2)) # 5 points in 2D space

print("\nX:\n", X)



C = np.random.random((2, 2)) # 2 centroids, also in 2D space

print("\nC:\n", C)

     

for c in C:

   diff = X - c # Difference between X and c

   # as c is an only 1D slice of C, is broadcasted over X along axis 0 (up->down)

   

   dist = np.linalg.norm(

       diff, # Apply norm on differences

       axis=1 # Apply ONLY along axis 1 (left->right, i.e. the coordinates of each point)

   )



   print(f"\nDistances of X to centroid {c}:")

   print(dist)

   


X:
 [[0.46831726 0.15990121]
 [0.80776656 0.14449807]
 [0.48056012 0.37054238]
 [0.81449338 0.07546626]
 [0.16414265 0.05398996]]

C:
 [[0.06235401 0.52615308]
 [0.25325276 0.22018722]]

Distances of X to centroid [0.06235401 0.52615308]:
[0.54676008 0.83743681 0.4462186  0.87683079 0.48301028]

Distances of X to centroid [0.25325276 0.22018722]:
[0.2233543  0.5596556  0.27253497 0.57959916 0.18857927]
